server:
  error:
    path: /user/error
    whitelabel:
      enabled: false
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/securecapita
    password: password
    username: root
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
  sql:
    init:
      mode: never
      continue-on-error: false
vonage:
  api:
    key: ${VONAGE_KEY}
    secret: ${VONAGE_SECRET}

jwt:
  secret: ${JWT_SECRET}